# site settings
title:  EuroTrade Gateway UG (hb)
subtitle: Market Access Management
email: contact@eurotrade-gateway.com
description: VAT | Customs | EPR | Packaging | LUCID | WEEE | Batteries | Sales Report Analysis 
baseurl: "" # the subpath of your site, e.g. /blog
url: https://eurotrade-gateway.com
author: Dirk Schmidt-Waerdt, CEO of EuroTrade Gateway UG (hb)
street_address: EUROTEC-Ring 15
city: Moers
state: NRW
zip_code: 47445
country: Germany
phone: +49 179 4930099

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/dischmidt
  GitLab:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/market-access-europe
  Twitter: 
  X: https://x.com/ecommerceEU
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed
  quiet_deps: true    # get rid of deprecation warnings


exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- deploy.sh
- "*.bak"

collections:
  portfolio:
    output: true
  
